(() => {
  'use strict';
  const config=window.VANEY_REVIEW_SETTINGS||{},preview=location.protocol==='file:';
  const posts=[...document.querySelectorAll('section.post')],controls=new Map(),state=new Map();
  const notice=document.createElement('p');notice.className='review-notice';notice.setAttribute('role','status');
  document.querySelector('.intro').append(notice);
  const refreshButton=document.createElement('button');refreshButton.type='button';refreshButton.className='review-refresh';refreshButton.textContent='Refresh approvals and comments';notice.after(refreshButton);
  let loading=false,ready=preview,comments=[];
  const key='vaney-prelaunch-20261006-local-preview';
  if(preview){try{const saved=JSON.parse(sessionStorage.getItem(key)||'{}');for(const [id,row] of Object.entries(saved.approvals||{}))state.set(id,row);comments=saved.comments||[];}catch(_){} }
  function persistPreview(){if(preview)try{sessionStorage.setItem(key,JSON.stringify({approvals:Object.fromEntries(state),comments}));}catch(_){} }
  const make=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text)el.textContent=text;return el;};
  function paint(id){const c=controls.get(id),row=state.get(id);if(c.busy)return;const approved=row?.approved===true;c.input.checked=approved;c.input.disabled=!ready;c.host.classList.toggle('is-approved',approved);c.wrap.classList.toggle('is-approved',approved);c.badge.classList.toggle('is-approved',approved);c.badge.textContent=approved?(preview?'Preview approved':'Approved'):'Pending approval';c.status.textContent=preview?'Preview only · not shared':row?(approved?'Approved':'Reopened')+' · '+new Date(row.updatedAt).toLocaleString():ready?'Awaiting approval':'Shared connection pending';c.send.disabled=!ready;}
  function drawComments(){for(const [id,c] of controls){c.list.replaceChildren();const rows=comments.filter(x=>x.post===id);if(!rows.length)c.list.append(make('p','muted','No comments yet.'));for(const row of rows){const item=make('article','comment-item');const time=make('time','',new Date(row.createdAt).toLocaleString());item.append(time,make('p','',row.message));c.list.append(item);}}}
  async function request(url,body){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),15000);try{const response=await fetch(url,{cache:'no-store',signal:abort.signal,...(body?{method:'POST',body:new URLSearchParams(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not save.');return data;}finally{clearTimeout(timer);}}
  async function refresh(){if(loading)return;if(preview){notice.textContent='Local layout preview: approvals turn green and comments can be tried here. These preview changes are not shared with Vaney or other browsers.';drawComments();for(const id of controls.keys())paint(id);return;}
    if(!config.approvalsEndpoint||!config.commentsEndpoint){notice.textContent='Shared approvals and comments are awaiting connection. GitHub upload alone does not enable sharing.';return;}
    loading=true;try{const [a,b]=await Promise.all([request(config.approvalsEndpoint),request(config.commentsEndpoint)]);if(!a.approvals||!Array.isArray(b.comments))throw Error('Invalid response');for(const row of Object.values(a.approvals)){if(controls.has(row.post)){const old=state.get(row.post);if(!old||Number(row.id)>=Number(old.id))state.set(row.post,row);}}comments=b.comments.filter(x=>controls.has(x.post));ready=true;for(const id of controls.keys())paint(id);drawComments();notice.textContent='Approvals and comments are shared across browsers · refresh automatically every 10 seconds.';}catch(_){notice.textContent='Shared feedback could not refresh. Your unsent comments remain in place. Try Refresh.';}finally{loading=false;}}
  for(const host of posts){const id=host.id,wrap=host.querySelector('.review-controls'),input=wrap.querySelector('input'),status=wrap.querySelector('.review-status'),badge=wrap.querySelector('.badge'),board=host.querySelector('.comment-board'),list=board.querySelector('.comment-list'),form=board.querySelector('form'),message=form.querySelector('textarea'),send=form.querySelector('button[type="submit"]'),feedback=board.querySelector('.comment-status');const c={host,wrap,input,status,badge,list,send,busy:false};controls.set(id,c);
    input.onchange=async()=>{const approved=input.checked;c.busy=true;input.disabled=true;status.textContent='Saving…';let error='';try{let row;if(preview){row={id:Date.now(),post:id,approved,updatedAt:new Date().toISOString()};}else{const d=await request(config.approvalsEndpoint,{post:id,approved:String(approved),requestId:crypto.randomUUID()});if(!d.approval||d.approval.post!==id||d.approval.approved!==approved)throw Error('Approval was not confirmed');row=d.approval;}state.set(id,row);persistPreview();}catch(_){error='Approval was not saved. Refresh and try again.';}finally{c.busy=false;paint(id);if(error)status.textContent=error;}};
    let requestId=null,lastText='';form.onsubmit=async event=>{event.preventDefault();if(!ready||!form.reportValidity())return;const text=message.value.trim();if(!text||text.length>2000)return;if(text!==lastText||!requestId){lastText=text;requestId=crypto.randomUUID();}send.disabled=true;feedback.textContent='Saving…';try{let row;if(preview){row={id:requestId,post:id,message:text,createdAt:new Date().toISOString()};}else{const data=await request(config.commentsEndpoint,{post:id,message:text,requestId,website:form.querySelector('[name="website"]').value});if(!data.comment||data.comment.post!==id)throw Error('Comment was not confirmed');row=data.comment;}if(!comments.some(x=>x.id===row.id))comments.push(row);persistPreview();drawComments();message.value='';requestId=null;feedback.textContent=preview?'Preview comment added · not shared.':'Comment saved and shared.';}catch(_){feedback.textContent='Could not save. Your comment is still here; please try again.';}finally{send.disabled=!ready;}};
    board.querySelector('.comment-refresh').onclick=refresh;paint(id);
  }
  refreshButton.onclick=refresh;refresh();setInterval(()=>{if(!document.hidden)refresh();},config.refreshMs||10000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
})();
